### ISSUE TITLE
problem with file system

### ISSUE THREAD

**Issue by francescoagati** [xforty/vagrant-rails#2]
mount -t vboxsf -o uid=`id -u vagrant`,gid=`id -g vagrant` v-csc-2 /tmp/vagrant-chef-1/chef-solo-2/cookbooks

The following SSH command responded with a non-zero exit status.
Vagrant assumes that this means the command failed!

mount -t vboxsf -o uid=`id -u vagrant`,gid=`id -g vagrant` v-csc-2 /tmp/vagrant-chef-1/chef-solo-2/cookbooks

**Comment by dkingofpa** [comment]
Make sure your `cookbooks` folder exists on the host.  Before running `vagrant up` for the first time, you need to run `librarian-chef install` to create and download all the chef cookbooks.
